### ISSUE TITLE
oundError: [Errno 2] No such file or directory: '/apdcephfs_cq2/share_1290939/kitbai/mind-vis/datasets/eeg_5_95_std.pth'

### ISSUE THREAD

**Issue by ChiShengChen** [bbaaii/DreamDiffusion#28]
I met the error when I run the gen_eval_eeg.py, how do I find the hard-coded path to change to my local folder?

`python3 code/gen_eval_eeg.py --dataset EEG --model_path  pretrains/generation/checkpoint.pth
`

```
(dreamdiffusion) meow@meow-System-Product-Name:~/DreamDiff/DreamDiffusion$ python3 code/gen_eval_eeg.py --dataset EEG --model_path  pretrains/generation/checkpoint.pth
{'seed': 2022, 'root_path': '../dreamdiffusion/', 'output_path': '/apdcephfs_cq2/share_1290939/kitbai/mind-vis/exps/results/generation/22-02-2023-16-37-32', 'kam_path': '/apdcephfs_cq2/share_1290939/kitbai/mind-vis/datasets/data/Kamitani/npz', 'bold5000_path': '/apdcephfs_cq2/share_1290939/kitbai/mind-vis/datasets/data/BOLD5000', 'eeg_signals_path': '/apdcephfs_cq2/share_1290939/kitbai/mind-vis/datasets/eeg_5_95_std.pth', 'splits_path': '/apdcephfs_cq2/share_1290939/kitbai/mind-vis/datasets/block_splits_by_image_single.pth', 'roi': 'VC', 'patch_size': 4, 'embed_dim': 1024, 'depth': 24, 'num_heads': 16, 'mlp_ratio': 1.0, 'pretrain_gm_path': '../dreamdiffusion/pretrains/', 'dataset': 'EEG', 'kam_subs': ['sbj_3'], 'bold5000_subs': ['CSI4'], 'pretrain_mbm_path': '../dreamdiffusion/results/eeg_pretrain/19-02-2023-08-48-17/checkpoints/checkpoint.pth', 'img_size': 256, 'batch_size': 4, 'lr': 5.3e-05, 'num_epoch': 5000, 'precision': 32, 'accumulate_grad': 1, 'crop_ratio': 0.2, 'global_pool': False, 'use_time_cond': True, 'eval_avg': True, 'num_samples': 5, 'ddim_steps': 250, 'HW': None, 'model_meta': None, 'checkpoint_path': None, 'logger': None, 'trainer': None}
Traceback (most recent call last):
  File "code/gen_eval_eeg.py", line 95, in <module>
    dataset_train, dataset_test = create_EEG_dataset(eeg_signals_path = config.eeg_signals_path, splits_path = splits_path, 
  File "/home/meow/DreamDiff/DreamDiffusion/code/dataset.py", line 396, in create_EEG_dataset
    dataset_train = EEGDataset(eeg_signals_path, image_transform[0], subject )
  File "/home/meow/DreamDiff/DreamDiffusion/code/dataset.py", line 308, in __init__
    loaded = torch.load(eeg_signals_path)
  File "/home/meow/anaconda3/envs/dreamdiffusion/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/meow/anaconda3/envs/dreamdiffusion/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/meow/anaconda3/envs/dreamdiffusion/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/apdcephfs_cq2/share_1290939/kitbai/mind-vis/datasets/eeg_5_95_std.pth'
```

**Comment by denlolsauce** [comment]
I have the exact same error, i dont knwo whats wrong

**Comment by NZW666666** [comment]
me too,i donot know how to deal with it

**Comment by bobwangPKU** [comment]
Add lines at line 70 in `gen_eval_eeg.py` to update data path. The generation code use the config contained in the provided checkpoint. 
```
config.eeg_signals_path = '../datasets/eeg_5_95_std.pth'
config.splits_path = '../datasets/block_splits_by_image_single.pth'
```

**Comment by yangjianger** [comment]
It can't run. The author's project is too messy and has various problems.
