### ISSUE TITLE
module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by FreeStyleFreeLunch** [bbaaii/DreamDiffusion#35]
Traceback (most recent call last):                                                                                                                                                            
  File "code/stageA1_eeg_pretrain.py", line 294, in <module>                                                                                                                                  
    main(config)                                                                                                                                                                              
  File "code/stageA1_eeg_pretrain.py", line 141, in main                                                                                                                                      
    model = MAEforEEG(time_len=dataset_pretrain.data_len, patch_size=config.patch_size, embed_dim=config.embed_dim,                                                                           
  File "/home/feihonghe/workspace/dreamdiffusion/DreamDiffusion-main/code/sc_mbm/mae_for_eeg.py", line 99, in __init__                                                                        
    self.initialize_weights()                                                                                                                                                                 
  File "/home/feihonghe/workspace/dreamdiffusion/DreamDiffusion-main/code/sc_mbm/mae_for_eeg.py", line 104, in initialize_weights                                                             
    pos_embed = ut.get_1d_sincos_pos_embed(self.pos_embed.shape[-1], self.num_patches, cls_token=True)                                                                                        
  File "/home/feihonghe/workspace/dreamdiffusion/DreamDiffusion-main/code/sc_mbm/utils.py", line 15, in get_1d_sincos_pos_embed                                                               
    pos_embed = get_1d_sincos_pos_embed_from_grid(embed_dim, grid_l)                                                                                                                          
  File "/home/feihonghe/workspace/dreamdiffusion/DreamDiffusion-main/code/sc_mbm/utils.py", line 27, in get_1d_sincos_pos_embed_from_grid                                                     
    omega = np.arange(embed_dim // 2, dtype=np.float)                                                                                                                                         
  File "/home/feihonghe/anaconda3/envs/dreamdiffusion/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__                                                                
    raise AttributeError(__former_attrs__[attr])                                                                                                                                              
AttributeError: module 'numpy' has no attribute 'float'.

**Comment by UlysseDurand** [comment]
I solved this issue by specifying the numpy version in env.yaml

numpy==1.19.5

And reinstall the conda environment
