### ISSUE TITLE
Error when running stageA1_eeg_pretrain.py file.

### ISSUE THREAD

**Issue by quoccuong75** [bbaaii/DreamDiffusion#37]
When I run the stageA1_eeg_pretrain.py file, I get this error:

Traceback (most recent call last):
File "preproduce_dreamdiffusion/code/stageA1_eeg_pretrain.py", line 304, in <module>
main(config)
File "preproduce_dreamdiffusion/code/stageA1_eeg_pretrain.py", line 130, in main
dataset_pretrain = eeg_pretrain_dataset(path='../preproduce_dreamdiffusion/datasets/mne_data/', roi=config.roi,
File "preproduce_dreamdiffusion/code/dataset.py", line 129, in __init__
assert len(self.input_paths) != 0, 'No data found'
AssertionError: No data found

Can anyone tell me how to fix this error? How to add pretrain dataset from Moabb in to run so?

**Comment by Autumn2323** [comment]
同问

**Comment by zhengzhent** [comment]
> When I run the stageA1_eeg_pretrain.py file, I get this error:
> 
> Traceback (most recent call last): File "preproduce_dreamdiffusion/code/stageA1_eeg_pretrain.py", line 304, in main(config) File "preproduce_dreamdiffusion/code/stageA1_eeg_pretrain.py", line 130, in main dataset_pretrain = eeg_pretrain_dataset(path='../preproduce_dreamdiffusion/datasets/mne_data/', roi=config.roi, File "preproduce_dreamdiffusion/code/dataset.py", line 129, in **init** assert len(self.input_paths) != 0, 'No data found' AssertionError: No data found
> 
> Can anyone tell me how to fix this error? How to add pretrain dataset from Moabb in to run so?

Have you solve this problem?

**Comment by zhengzhent** [comment]
> When I run the stageA1_eeg_pretrain.py file, I get this error:
> 
> Traceback (most recent call last): File "preproduce_dreamdiffusion/code/stageA1_eeg_pretrain.py", line 304, in main(config) File "preproduce_dreamdiffusion/code/stageA1_eeg_pretrain.py", line 130, in main dataset_pretrain = eeg_pretrain_dataset(path='../preproduce_dreamdiffusion/datasets/mne_data/', roi=config.roi, File "preproduce_dreamdiffusion/code/dataset.py", line 129, in **init** assert len(self.input_paths) != 0, 'No data found' AssertionError: No data found
> 
> Can anyone tell me how to fix this error? How to add pretrain dataset from Moabb in to run so?

Have you solved the problem, please?
